### PR TITLE
Expand levels scope to include floatingpoint lesson

### PR DESCRIPTION
**Pull request by szymon-rd**
@propensive what about `primitives` lesson?

### CODE REVIEW

**Comment by propensive** [comment]
It should be "coming soon", no?

**Comment by propensive** [comment]
By the way, I just saw you made the same fix to the scope as I'm about to make, though I'm rolling stones more text into the lesson too, which I realised was missing... should be ready in about 5-10 minutes, but I guess the merge will be trivial anyway.

**Comment by kusmierz** [comment]
Dunno, is it today’s lesson?

Adam
On 16 Feb 2021, 15:58 +0100, Jon Pretty <notifications@github.com>, wrote:
> It should be "coming soon", no?
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
Email correspondence is considered personal data processing. Check out our 
Privacy Policy <https://virtuslab.com/gdpr> for details about the 
controller of your data and your rights according to GDPR/RODO.

**Comment by propensive** [comment]
*"rolling some more text". No Rolling Stones involved. ;)

**Comment by szymon-rd** [comment]
I made another commit to include primitives lesson. `comingSoon` lessons also need to be in the levels' scope

**Pull request merged**
